### ISSUE TITLE
Mongo DB connection recommendation

### ISSUE THREAD

**Issue by felixcheruiyot** [postatum/lets-go#1]
Hi there,
I'm also learning golang and I hope to create a working API soon. I'm getting some inspiration from your repo but one concern though and where I need your advise:
Is it good to open and close Mongo connection for every request or rather Dial it only once and use it as a pool in the rest of the resource.

I'm thinking of opening it at the main() and just call it in the other files but I cannot figure out the best way to do so. Is it possible to create an interface that will pass the session variable to the rest of the resource? Please let me know what are your thoughts.

**Comment by postatum** [comment]
Hi Felix,

Thanks for the question. I'm glad if my repo helps you in any way.

I guess you've already figured out your question, but if not:
I didn't use "mgo" that much so I did a research and found an advice on this issue given by core developer of "mgo": http://stackoverflow.com/a/26576589

**Comment by felixcheruiyot** [comment]
Thanks Artem for your response. 

I like the way you have structured your code, and I'm borrowing a lot from it. 

On the mgo session, I did it in a similar manner as suggested at StackOverflow, and getting the same response from the plugin's core dev gives assurance I'm still on the right track.
Thank you for finding time to go through it. Good day.

**Comment by postatum** [comment]
You are welcome, Felix :)
